### ISSUE TITLE
Load all CDN assets via HTTPS

### ISSUE THREAD

**Issue by coliff** [awslabs/aws-js-s3-explorer#10]
RE: Protocol-relative URL
Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.

Allowing the snippet to request over HTTP opens the door for attacks like the GitHub Man-on-the-side attack.

**Comment by john-aws** [comment]
Source: https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by coliff** [comment]
Made a PR for this #12

**Comment by john-aws** [comment]
Thanks for fix and PR!
