### ISSUE TITLE
cors policy in README doesn't work

### ISSUE THREAD

**Issue by gurugeek** [awslabs/aws-js-s3-explorer#101]
<img width="792" alt="Bildschirmfoto 2021-07-27 um 02 11 58" src="https://user-images.githubusercontent.com/1631146/127075104-5a0a702c-9ba5-43b7-9abb-3e48a9b76c78.png">

I just copied from the README the cors policy and it is not accepted. It appears to be an invalid JSON (also confirmed by the JSON validator). 

Thanks for your help.

**Comment by gurugeek** [comment]
figure it out, my mistake

**Comment by john-aws** [comment]
The new CORS policy format is JSON and begins and ends with square (array) brackets, which is valid JSON. Did you miss the closing square bracket?

Also, where are you entering this policy? That doesn't look like the CORS policy input field. Can you clarify what S3 console path you took to get there? Thanks.

**Comment by john-aws** [comment]
Ah, our posts crossed. OK, glad you've resolved the issue.
