### ISSUE TITLE
README.md CORS config typo (v2-alpha)

### ISSUE THREAD

**Issue by c-stephenson** [awslabs/aws-js-s3-explorer#102]
JSON error in CORS config for the "ExposeHeaders" section, the final member "Date" is closed with a single quote instead of a double quote.

**Comment by john-aws** [comment]
@c-stephenson Thanks for reporting this.

**Comment by c-stephenson** [comment]
you are welcome.
great little web app, works perfect for my use case!
c.
    On Sunday, 8 August 2021, 05:45:03 PM GMT+1, john ***@***.***> wrote:  
 
 


@c-stephenson Thanks for reporting this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
