### ISSUE TITLE
Question: is there a way to specify service endpoint (endpoint URL)?

### ISSUE THREAD

**Issue by tomers** [awslabs/aws-js-s3-explorer#107]

**Comment by john-aws** [comment]
This capability is not present in the existing code, for the sake of simplicity for the most common use cases, but you could investigate enhancing your own fork of the code, for example to change the following [code](https://github.com/awslabs/aws-js-s3-explorer/blob/master/index.html#L180):

    var s3 = new AWS.S3();

to:

    var s3 = new AWS.S3({endpoint: 'https://newendpoint'});

**Comment by smhotz** [comment]
@john-aws

Are you saying AWS.S3 already accepts an endpoint parameter, and the change is simple ... or that AWS.S3 class could be re-factored to add that feature (somewhat less simple)?

For what it's worth, consider this another S3 user -- with a hybrid application where an on-premise S3-compatible service is the "front end", and AWS/S3 provides redundant offsite storage.

cheers (& thanks),
s.h.

**Comment by smhotz** [comment]
Ok, apologies for being lazy ... i see endpoint is an option to the constructor.

Follow-up:
Any experience (i.e. difficulty estimate) in using a non-AWS endpoint ?

thanks (again),
s.h.

**Comment by john-aws** [comment]
> Any experience (i.e. difficulty estimate) in using a non-AWS endpoint ?

Unfortunately not. It will depend on the level of API compatibility of the S3 emulation, I would think. Easy to do a quick test, if you have such an endpoint. Interested to hear your progress, if you go that route.

**Comment by tomers** [comment]
You can simply run `moto` docker (https://github.com/spulec/moto) locally, and there you could set endpoint URL to be `http://moto:5000`.
