### ISSUE TITLE
Question: promptForBucketInput

### ISSUE THREAD

**Issue by jaaayyy** [awslabs/aws-js-s3-explorer#112]
Hello,

Which part of the index.html should I modify so that the users can directly view the objects & subfolders of the bucket?
Removing the need to input the bucket name -- like this for example: https://dj2taa9i652rf.cloudfront.net/

Regards,

**Comment by danil-smirnov** [comment]
You have resolved this already?

E.g. https://dj2taa9i652rf.cloudfront.net/cdc-moderna-vaccine-distribution/csv/cdc-moderna-covid-19-vaccine-distribution-by-state.csv is directly accessible.

**Comment by danil-smirnov** [comment]
@jaaayyy Open the `index.html` file and search for `var s3exp_config` - there you can set the bucket and the region.

**Comment by jaaayyy** [comment]
got it working now .... thanks!!

**Comment by john-aws** [comment]
@danil-smirnov thank you for helping.
