### ISSUE TITLE
Feature Request: Last modified for folders

### ISSUE THREAD

**Issue by tobilen** [awslabs/aws-js-s3-explorer#21]
I really like this project!

One thing i'd like to see is "last modified" timestamps for folders though. I know this is a problem because the API doesn't give us more than a name for folders. I think there would have to be some fetching and filtering of files within a folder, finding the most recent timestamp and displaying that.

**Comment by john-aws** [comment]
Yes, this could be problematic for prefixes with large numbers of objects. Will look into it, however, as it seems like a useful feature.
