### ISSUE TITLE
Feature Request: Filter by metadata

### ISSUE THREAD

**Issue by cbates291** [awslabs/aws-js-s3-explorer#24]
Hello!

This is not something major and im not sure if its possible with potential API limitations, etc.

Do you think it would be possible to have a filter for metadata tags, etc? I was just thinking that if you tagged certain items or certain items were auto tagged, it would be cool to be able to filter by that metadata information as well as timestamp, name, etc.

Not sure how complicated that would be, etc. but just thought I would ask.

Thanks!

**Comment by john-aws** [comment]
Unfortunately the `listObjects()` request that is used to enumerate objects in a bucket does not return object metadata and there is no simple API to search metadata. We would have to issue a HEAD request to every object individually to retrieve its metadata and then implement search locally.

That said, I like the idea so will leave this open for now.

**Comment by AdamBD** [comment]
Seconding this request. Applications that have objects originating from end users can be categorized into further application or user defined 'categories'. For example images uploaded by users with image 'tags'. The s3 prefix system is too limiting for such a use-case. Being able to apply meta-data and then filter by such would be invaluable!

**Comment by msslava** [comment]
Hi! Tell me, is there a way to work with object versions using this UI? Versioning of objects is quite popular and it would be nice to have the ability to download a specific version of an object from a bucket.
Thanks!

**Comment by john-aws** [comment]
@msslava sorry, but S3 Explorer does not currently support object versions and there are no plans at present to add this feature.
