### ISSUE TITLE
Weird filename on Download

### ISSUE THREAD

**Issue by andrew80k** [awslabs/aws-js-s3-explorer#25]
Hoping someone can help me here...

I'm seeing some weird filenames when downloading from the bucket using this tool.  

I'm expecting just the file, with just the filename, but instead I'm getting a file with the complete path tacked on with a bunch of percentages in the filename.  

Example:

```
https://mybucket.s3.amazonaws.com/MAIN%2F2018.05.10-23_00_01%2FInstaller%2FSetup.exe
```

I'm expecting to just get the Setup.exe.  I've been running this for more than a month and I don't recall seeing this happen before.  Looking at the developer console in chrome I see:

```
target href=https://my-bucket.s3.amazonaws.com/MAIN%2F2018.05.07-10_52_08%2FInstaller%2FSetup.exe
```

Anyway to resolve this?

**Comment by john-aws** [comment]
Thank you for the report. This looks to have been introduced by #18. You could revert that change temporarily, while we investigate.
