### ISSUE TITLE
Do you have any idea if I don't want to do public bucket?

### ISSUE THREAD

**Issue by Pongchaiwat** [awslabs/aws-js-s3-explorer#26]
Do you have any idea if I don't want to do public bucket?

**Comment by john-aws** [comment]
Hi, a couple of people have asked for this and we are tracking the request in #11. There are also some ideas in the comments in that issue (e.g. how to specify source IP restrictions) that might help in certain cases.

**Comment by john-aws** [comment]
@Pongchaiwat Hi, I have uploaded an alpha of version 2 of S3 Explorer that can be used with private S3 buckets. Please see comments in #11.
