### ISSUE TITLE
CORS for Read-Only S3 Bucket section in readme.md not working

### ISSUE THREAD

**Issue by turjachaudhuri** [awslabs/aws-js-s3-explorer#32]
BRANCH : v2-alpha

I have setup the buckets in S3 as per the readme instructions . In the CORS sections of the readme it is mentioned 

If you intend to allow read-only access from BUCKET1, which hosts S3 Explorer, to BUCKET2, then you will need to supply a CORS configuration on BUCKET2 that permits HEAD and GET operations, for example:

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>https://s3.amazonaws.com</AllowedOrigin>
    <AllowedOrigin>https://BUCKET1.s3.amazonaws.com</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>x-amz-meta-custom-header</ExposeHeader>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <ExposeHeader>date</ExposeHeader>
  </CORSRule>
</CORSConfiguration>

My BUCKET1 is aws-js-s3-explorer.

However , if I provide CORS origin in BUCKET2 CORS properties as     <AllowedOrigin>https://BUCKET1.s3.amazonaws.com</AllowedOrigin>
the setup is not working and I am getting CORS error . 

Changing it to : 
<AllowedOrigin>https://aws-js-s3-explorer.s3.ap-south-1.amazonaws.com</AllowedOrigin>

works for me . 

So , should the readme.md be updated to 
    <AllowedOrigin>https://BUCKET1.s3.REGION1.amazonaws.com</AllowedOrigin>
from
    <AllowedOrigin>https://BUCKET1.s3.amazonaws.com</AllowedOrigin>

where REGION1 is the region of BUCKET1?

**Comment by john-aws** [comment]
Hi, thanks for the report and for going the extra step to resolve the problem. We will review the documentation and make corrections. Thanks again.

**Comment by john-aws** [comment]
Hi, the README does attempt to cover this scenario. In the 'Static Website Hosting' section of the README, it indicates that you will also need to modify the CORS configuration:

> Or as follows, if in a bucket outside of US East (N. Virginia):
> 
> ```xml
>   <AllowedOrigin>https://BUCKET-NAME.s3.us-west-2.amazonaws.com</AllowedOrigin>
> ```
> 

Does that cover your case?
