### ISSUE TITLE
Hosting the JS app outside of AWS

### ISSUE THREAD

**Issue by rinogo** [awslabs/aws-js-s3-explorer#35]
The documentation extensively discusses how to deploy this JS app to an AWS bucket in order to manage other AWS buckets.

I'm interested in integrating this app into my existing application that is hosted outside of AWS.

This is a supported use case, correct? Are there any problems I'll run into by hosting the files of aws-js-s3-explorer on a "traditional" webserver?

Thank you!

**Comment by john-aws** [comment]
Hi, the project was originally designed to operate as a statically-hosted website in a public S3 bucket. This made it simple to deploy and cheap to run (no web servers).

Some users wanted an option that would work with non-public buckets so we created a [v2-alpha branch](https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha) for that use case.

All that said, I see no fundamental issues with hosting it outside of AWS. You would likely need to make a few modifications, for example to the code that currently auto-detects which S3 bucket it should query. Good luck and tell us if we can help.

**Comment by avoll** [comment]
Hi @rinogo, did you have a chance to make it work on your own web host?  Would appreciate a few words on your experience integrating it. Planning to do the same. 
Thank you!

**Comment by rinogo** [comment]
No, I didn’t. Instead, we used the API to build something a little more home-grown and appropriate for our needs. Good luck! :)

**Comment by avoll** [comment]
Got it, thank you :)
