### ISSUE TITLE
Doesn't work with IE11

### ISSUE THREAD

**Issue by crosspoints** [awslabs/aws-js-s3-explorer#37]
The table couldn't show with IE11. Chrome and Firefox, Edge were OK.
I changed the using version of dataTables. It was OK.

https://github.com/crosspoints/aws-js-s3-explorer/commit/8154e3bed270da3efe79bebdae1d9ea1bcffbc52#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by john-aws** [comment]
Thank you very much for the fix.
