### ISSUE TITLE
File upload does not work for files greater than 5Mb

### ISSUE THREAD

**Issue by danil-smirnov** [awslabs/aws-js-s3-explorer#38]
This relates to version _v2-alpha_ which allows files upoading.
The feature works just fine for files smaller than 5Mb but fails in case of larger one.
The error is as follows:

`Access to XMLHttpRequest at 'https://bucket.s3.amazonaws.com/test2/test10Mb.file?uploads' from origin 'https://site.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by danil-smirnov** [comment]
This issue has been resolved by adding POST method to the bucket CORS configuration:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://dev.retention.live</AllowedOrigin>
    <AllowedOrigin>https://dev.office.retention.live</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>x-amz-meta-custom-header</ExposeHeader>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <ExposeHeader>date</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
README file should be updated to reflect this.

**Comment by john-aws** [comment]
Thank you very much for the fix. Will push shortly.
