### ISSUE TITLE
[v2-alpha] Feature request: upload files into a new folder

### ISSUE THREAD

**Issue by danil-smirnov** [awslabs/aws-js-s3-explorer#39]
This is a feature request for v2-alpha branch which supports file uploads.

Currently, it's not possible to upload a whole folder to S3 bucket using the tool nor to create a new folder and then navigate into it. This makes impossible to upload files into a folder if it doesn't pre-exist in S3 bucket.

**Comment by john-aws** [comment]
Hi, I have added a basic 'Add Folder' feature that will create a zero-sized S3 object (e.g. wallpaper/animals/dogs/) representing a folder. You can then navigate into this folder and add files.

To use this, click the 'Add folder' button adjacent to the 'Info' button (top right).

**Comment by syndic8-joe** [comment]
Will there be support for drag-and-drop upload of a folder (with or without contents)?  I would also very much like to see this feature added; similarly, the ability to delete a folder would be very helpful.

**Comment by danil-smirnov** [comment]
Hi @john-aws, thank you for the update: tested, works like a charm!

But @syndic8-joe is right - a folder created can't be deleted anyhow...
¯\_(ツ)_/¯

I hope this is resolvable...

**Comment by john-aws** [comment]
@syndic8-joe when deleting a folder, are you hoping that it will delete the contents of the folder as well? Or simply delete the folder if empty, but if not empty then fail (asking you to delete the contents first)?

**Comment by danil-smirnov** [comment]
@john-aws This can be different for Folder and Flat view mode: for the first one I believe we want to simulate usual file explorer behaviour to delete folder along with its content. For the latter we probably should fail and ask...

**Comment by syndic8-joe** [comment]
I suppose the most well-rounded design would (action upon hitting the delete button) delete the folder if it's empty, and if it is not, prompt the user to confirm deletion (display a warning that there are contents, and those will also be deleted if confirmed).

For my purposes, it would suffice to delete regardless of whether or not the folder has contents, just as you'd expect in a native OS folder interaction.

We have folders with many thousands of files, so a deletion of the contents first would not be very practical.

**Comment by danil-smirnov** [comment]
@syndic8-joe In current implementation a deletion of
