### ISSUE TITLE
Change Search label

### ISSUE THREAD

**Issue by kayaademogullari** [awslabs/aws-js-s3-explorer#4]
This is very simple and awkwardly question, I know but, cannot figured it out and stack. How can I change "Search" and "Show"... "entries" labels to different language? Where are their location?

**Comment by coliff** [comment]
That is managed by the https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js file.

**Comment by kayaademogullari** [comment]
Thank you very much.
