### ISSUE TITLE
Hide error after timeout or success

### ISSUE THREAD

**Issue by benyanke** [awslabs/aws-js-s3-explorer#42]
Currently the errors stay on the screen indefinitely, it seems. It would be great to have them hide after a given time, or after another successful action.

**Comment by john-aws** [comment]
Hi, apologies for the delayed response here. Are you referring to the master branch or v2-alpha?

**Comment by benyanke** [comment]
I'm on the alpha branch.

**Comment by john-aws** [comment]
OK, thanks. I'm assuming that you mean the error messages that look like this:

<img width="751" alt="err02" src="https://user-images.githubusercontent.com/3178883/55657561-936d4b80-57c8-11e9-89cd-0e64d44f9d95.png">

It is actually possible to close these using the small X at the top right. Would that suffice? If not, we could perhaps show a modal dialog with a subset of the error details (e.g. just the code/message) that you would then have to close to continue.

**Comment by benyanke** [comment]
Yes - that's correct. I'm not actually worried about the strict functionality here, but rather the user's experience. For example, does it make sense for this to still be showing after the user has completed 10-20 successful actions?

I like the modal idea - or at least hiding what is currently there the next time a user-initiated action completes without error.

**Comment by john-aws** [comment]
We now show a modal popup for any runtime error. The initial summary looks like this:

<img width="898" alt="42-summary" src="https://user-images.githubusercontent.com/3178883/57455535-5407a400-7239-11e9-9010-1acab81e2260.png">

If you click the `Advanced` button, you will see additional details, for example:

<img width="898" alt="42-detailed" src="https://user-images.githubusercontent.com/3178883/57455583-700b4580-7239-11e9-8162-df591c932558.png">
