### ISSUE TITLE
[v2-alpha] Folders drag-n-drop is broken

### ISSUE THREAD

**Issue by danil-smirnov** [awslabs/aws-js-s3-explorer#63]
Hi guys,

I'm afraid you have broken folders drag-n-drop feature with the [last commits](https://github.com/awslabs/aws-js-s3-explorer/pull/62)...

When drop the following files structure to the app:

```
Test
├── aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
│   └── jquery-ui-1.12.1.custom.zip
├── jquery-ui-1.12.1.customaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip
└── Test2
    └── jquery-ui-1.12.1.custom.zip

```
I previously saw this:

![Screenshot from 2019-08-03 13-09-03](https://user-images.githubusercontent.com/27999539/62410676-d2ce6c00-b5f1-11e9-9245-30ac66db01de.png)

But now I see this:

![Screenshot from 2019-08-03 13-10-23](https://user-images.githubusercontent.com/27999539/62410680-d9f57a00-b5f1-11e9-80cc-fd3fabdb8c6b.png)

I would suggest to revert the last commit until fixed.

**Comment by john-aws** [comment]
Hi, apologies that this introduced a problem. Rather than revert the previous commit, we'll take a look at fixing the problem that was introduced.

**Comment by danil-smirnov** [comment]
Hi @john-aws 
Somehow I've missed this update...
Tested now - works like a charm!
Thank you very much!
Closing the issue...
