### ISSUE TITLE
network faliure 

### ISSUE THREAD

**Issue by joamatab** [awslabs/aws-js-s3-explorer#65]
Im getting a network faliure despite having followed the steps'

![image](https://user-images.githubusercontent.com/4514346/65785439-3fa14680-e109-11e9-8824-3331063fec29.png)

If I hit advanced i get more details

![image](https://user-images.githubusercontent.com/4514346/65785621-a7f02800-e109-11e9-97fd-6e42d60063b7.png)

how can I fix it?

https://cyberduck.io works fine from my computer

**Comment by john-aws** [comment]
NetworkingError is commonly caused by a CORS misconfiguration so please review that. If you're sure that your CORS configuration and your S3 bucket policy are correct then please post details of both here, obfuscating the sensitive parts such as account numbers, bucket names, etc.

**Comment by john-aws** [comment]
Hi @joamatab, were you able to make any progress here?

**Comment by joamatab** [comment]
hi @john-aws 

im using nextcloud to access the s3 buckets

i think the issue was

also, how do you store the keys for accessing the s3 buckets? so you don't have to manually entry it every time ^^

**Comment by john-aws** [comment]
@joamatab we don't currently support persistent storage of credentials, and have no plans to add this as a feature. You could potentially fork the code and implement local storage persistence, but I would strongly recommend that it be encrypted and secured with some form of complex password that only the user knows.

**Comment by halfar-dbseer** [comment]
I think this happens due to CORS issue, look like you are serving your static website with http only and your CORS settings is using https.

"AllowedOrigins": [
    "https://BUCKET-NAME.s3.amazonaws.com"
  ]

you may need to try:
"AllowedOrigins": [
    "https://BUCKET-NAME.s3.amazonaws.com",
    "http://BUCKET-NAME.s3.amazonaws.com"
  ]

**Comment by john-aws** [comment]
@joamatab feel free to re-open if you were unable to resolve your issue, in which case please provide the aforementioned CORS policy information.
