### ISSUE TITLE
search option doesn't do  a nested search

### ISSUE THREAD

**Issue by karthikghan** [awslabs/aws-js-s3-explorer#66]
Hi team,

  we really like the simplicity of the tool. But we have terabytes of data in our bucket and its a great pain to search through the bucket, especially when you have files with keys that represent directories within directories.

I am unable to search for that type of files. Adding that feature will be immensely helpful

**Comment by john-aws** [comment]
Hi, can you give me a specific example? And are you using the Initial View setting of Folder or Bucket?

Also, is this related to [v1](https://github.com/awslabs/aws-js-s3-explorer) or [v2-alpha](https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha)?

**Comment by john-aws** [comment]
Hi @karthikghan, can you provide clear examples of what you're looking for here? Happy to help if we can. For now, I'll close the issue but please respond and re-open as needed.
