### ISSUE TITLE
Error accessing S3 bucket s3. Error: NetworkingError: Network Failure

### ISSUE THREAD

**Issue by davesade** [awslabs/aws-js-s3-explorer#7]
Hello,
I follow instructions, setting Bucket Policy and CORS accordingly.

Then I tried static website hosting via S3, but error appears:
`Error accessing S3 bucket s3. Error: NetworkingError: Network Failure`
In browser console I can see:
`aws-sdk-2.0.13.min.js:4 OPTIONS https://s3-share.amazonaws.com/?delimiter=%2F net::ERR_NAME_NOT_RESOLVED`

All files in my bucket are made public.

I am not sure, what I'm doing wrong, I suspect it might be CORS settings, which are in my case:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://MYBUCKETNAME.s3-website.eu-central-1.amazonaws.com</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>x-amz-meta-custom-header</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
I also tried to simply put URL of `index.html` file to browser (I have changed AllowedOrigin accordingly, but not sure if it actually do anything in that case), but the issue reappears again.

**Comment by john-aws** [comment]
Could you please try the following change to index.html around line 554. Change this:

```
    if (hostnames.length == 4) {
        bucket = hostnames[0];
        region = hostnames[1];
```

to this:

```
    if (hostnames.length >= 4) {
        bucket = hostnames[0];
        region = hostnames[hostnames.length - 3];
```

**Comment by Shayan2017** [comment]
is that issue resolved ? I am facing the same issue, but didn't find below section on index.html file 
if (hostnames.length == 4) {
        bucket = hostnames[0];
        region = hostnames[1];

**Comment by Tyler-Rendina** [comment]
SOCKS5 for ssh tunneling to private subnets will cause this issue (i.e., loading a glue script in the aws console).

**Comment by john-aws** [comment]
Hi @Tyler-Rendina, unclear how this relates specifically to the AWS JavaScript S3 Explorer project.

**Comment by Tyler-Rendina** [comment]
Hey @john-aws, I have a suspicion this is used to render scripts in Glue ETL on the AWS console.  When I searched the error this was the first link so I figured I'd add my specific case to the thread in case anyone else had the same issue.  This thread ultimately was the solution to my problem!

**Comment by john-aws** [comment]
Hi @Tyler-Rendina, the AWS JavaScript S3 Explorer project isn't part of the AWS console, but both could potentially yield a `NetworkingError: Network Failure` and one likely cause in both scenarios is a CORS misconfiguration.
