### ISSUE TITLE
federated users using saml 

### ISSUE THREAD

**Issue by darichailu** [awslabs/aws-js-s3-explorer#80]
is this solution compatible with IdPs?

**Comment by john-aws** [comment]
There is no web server here. The solution is a static web page. You could use AWS federation with your identity provider to retrieve AWS credentials and use those but it's not possible to automate the single sign-on flow.

**Comment by darichailu** [comment]
Thanks John,
Appreciate the answers. I was thinking about implementing this solution but
all my users don't have aws accounts. Based on your answer the only way is
to use access key and secure access keys.

**Comment by wparad** [comment]
This is actually doable with Cognito via #84 or #85, and is supported in other s3 explorers, such as [this one](https://github.com/rhosys/aws-s3-explorer/#aws-s3-explorer).

**Comment by wparad** [comment]
Cloned from this explorer, this one now supports Cognito: [aws s3 explorer](https://rhosys.github.io/aws-s3-explorer/)
