### ISSUE TITLE
handling multipart

### ISSUE THREAD

**Issue by darichailu** [awslabs/aws-js-s3-explorer#81]
can this solution handle multi-part upload/download for large files?

**Comment by john-aws** [comment]
Yes, we support multi-part upload and files larger than 5GB.

The solution uses the AWS JavaScript SDK's [managed upload feature](https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/). This:

> allows large buffers, blobs, or streams to be uploaded more easily and efficiently, both in Node.js and in the browser.
>
> The new AWS.S3.upload() function intelligently detects when a buffer or stream can be split up into multiple parts and sent to S3 as a multipart upload.

We don't actually handle the download. That's the browser's responsibility when fetching a pre-signed URL of the object in question.
