### ISSUE TITLE
[v2-alpha] Files list stays obsolete after upload cancelled

### ISSUE THREAD

**Issue by danil-smirnov** [awslabs/aws-js-s3-explorer#87]
Hi @john-aws 

I've integrated the [latest commit](https://github.com/awslabs/aws-js-s3-explorer/commit/f4b35eabae51a8aa6353e4d0559b4efab4a9c94d) into my setup and discovered a minor issue: after upload is partially done (some files are done, some cancelled) there no refresh of files list happens.

**Comment by john-aws** [comment]
Will take a look. Thanks for reporting this.

**Comment by john-aws** [comment]
Hi @danil-smirnov, I was unable to repro this. I uploaded 6 files of varying sizes. The smaller files completed (the progress indicator showed 100% and went green), then I hit Cancel. This cancelled the incomplete uploads, and then refreshed the underlying list of files so that it now included the small files that had been successfully uploaded. I tested this twice with the same results.

Can you provide repro instructions? Thanks.

**Comment by danil-smirnov** [comment]
@john-aws It's easily reproducible:

Empty folder:

<img width="1785" alt="Screenshot 2020-05-18 at 18 11 08" src="https://user-images.githubusercontent.com/27999539/82229492-2f0d3d00-9933-11ea-993a-4d9fa672bef7.png">

Added files:

<img width="1785" alt="Screenshot 2020-05-18 at 18 11 26" src="https://user-images.githubusercontent.com/27999539/82229549-45b39400-9933-11ea-8b27-bcce7adba756.png">

Canceled upload:

<img width="1785" alt="Screenshot 2020-05-18 at 18 11 38" src="https://user-images.githubusercontent.com/27999539/82229605-5fed7200-9933-11ea-8a2d-d45d79e1451a.png">

Empty folder still (no autorefresh):

<img width="1785" alt="Screenshot 2020-05-18 at 18 11 49" src="https://user-images.githubusercontent.com/27999539/82229666-6ed42480-9933-11ea-8aa7-e3fc90b479bc.png">

Files appeared after manual refresh:

<img width="1785" alt="Screenshot 2020-05-18 at 18 11 59" src="https://user-images.githubusercontent.com/27999539/82229706-785d8c80-9933-11ea-9513-2b77e35a2afb.png">

**Comment by danil-smirnov** [comment]
@john-aws Could it be the issue manifests itself when the _last_ file cancelled only?

**Comment by john-aws** [comment]
Fixed by https://github.com/awslabs/aws-js-s3-explorer/commit/e6fc63e4f4d11370f89fae927848911fca2e3f68.

**Comment by danil-smirnov** [comment]
Great @john-aws , confirming the fix, thanks!
