### ISSUE TITLE
Feature request: presigned URL authentication

### ISSUE THREAD

**Issue by acro5piano** [awslabs/aws-js-s3-explorer#88]
It would be great if users can authenticate with pre-signed URL.

https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

Use Case: we would like to show our S3 buckets for users with secure and simple way. AWS access key is needed to be handled carefully, and setting expiration minutes is easier with pre-signed URL than access key as far as I know.

**Comment by john-aws** [comment]
If I understand what's being requested here, it wouldn't work because a pre-signed URL can't provide access to an entire bucket of objects.

**Comment by acro5piano** [comment]
@john-aws Okay thanks
