### ISSUE TITLE
[v2-alpha] Upload button multiple clicks cause wildness

### ISSUE THREAD

**Issue by danil-smirnov** [awslabs/aws-js-s3-explorer#89]
Hi @john-aws !

I told you some time ago that I have incredible tester here.
She's just discovered a perfect bug I had no chance to find by myself due to lack of imagination. :)

This bug shows in case you click Upload button again while uploading a file. It seems another upload process starts in parallel with the ongoing one.

And after the second click one can not cancel an upload anymore.

Obviously Upload button must be disabled after the first click...

**Comment by john-aws** [comment]
Thanks for reporting this. The problem was introduced in e6fc63e4f4d11370f89fae927848911fca2e3f68.
