### ISSUE TITLE
Error accessing S3 bucket test-browse. Error: NetworkingError: Network Failure

### ISSUE THREAD

**Issue by jinthoa** [awslabs/aws-js-s3-explorer#92]
Hello, 

I followed the instruction for bucket policy and CORS configuration but I can't make this to work on my bucket. 

My bucket policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicListGet",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:List*",
                "s3:Get*"
            ],
            "Resource": [
                "arn:aws:s3:::test-browse",
                "arn:aws:s3:::test-browse/*"
            ]
        }
    ]
}
```

My CORS configuration:

```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
                    <CORSRule>
                      <AllowedOrigin>http://MY-BUCKET-NAME.s3-website-us-west-1.amazonaws.com</AllowedOrigin>
                      <AllowedMethod>HEAD</AllowedMethod>
                      <AllowedMethod>GET</AllowedMethod>
                      <AllowedHeader>*</AllowedHeader>
                      <ExposeHeader>ETag</ExposeHeader>
                      <ExposeHeader>x-amz-meta-custom-header</ExposeHeader>
                    </CORSRule>
</CORSConfiguration>
```

At the address: https://MY-BUCKET-NAME.s3-us-west-1.amazonaws.com/index.html, I get the following [error](https://prnt.sc/v07osn):

![v07osn](https://user-images.githubusercontent.com/3178883/96260505-1f029380-0f8d-11eb-8151-98ec6d030ef4.png)

At the address: https://s3.amazonaws.com/MY-BUCKET-NAME/index.html, I get [this](https://prnt.sc/v07p17):

![v07p17](https://user-images.githubusercontent.com/3178883/96260554-2fb30980-0f8d-11eb-8657-6dd5a92b2168.png)

At the address: http://MY-BUCKET-NAME.s3-website-us-west-1.amazonaws.com/, I get [this](https://prnt.sc/v07paq):

![v07paq](https://user-images.githubusercontent.com/3178883/96260590-3a6d9e80-0f8d-11eb-9e1c-07907015f1a5.png)

index.html is at the root of my bucket, guessing this is the right place. Any help would be appreciated, thanks.

**Comment by danil-smirnov** [comment]
The last error advises you haven't enabled "Static website hosting" feature in the bucket. The second issue is that you are trying to reach the bucket via https which is not supported by the mentioned feature at the moment as far as I know.

**Comment by john-aws** [comment]
Thanks for jumping in to help @danil-smirnov 

@jinthoa can you confirm that you followed the [Static Website Hosting instructions](https://github.com/awslabs/aws-js-s3-explorer#static-website-hosting)?

**Comment by jinthoa** [comment]
> The last error advises you haven't enabled "Static website hosting" feature in the bucket. The second issue is that you are trying to reach the bucket via https which is not supported by the mentioned feature at the moment as far as I know.

Thank you, it worked!
