### ISSUE TITLE
Upload Speed

### ISSUE THREAD

**Issue by gitsapuser** [awslabs/aws-js-s3-explorer#96]
It took about 15 minutes to upload a 1GB file even with the accelerated endpoint enabled.  Typically s3 upload times for me using the AWS console is about the same.  Is there a way to increase the upload time?

**Comment by john-aws** [comment]
I'd expect the upload time to be comparable to the awscli or the AWS S3 console over the same connection, and that's what I see in practice. Obviously, your ISP connection speed is going to play a large part in this.

I did a few quick tests: from a laptop over wifi where speedtest.net reports 150Mbps upload speed, I can upload 1GB in 70-90s (direct to S3, not using accelerated endpoint). The same upload from awscli took a similar amount of time and was a little slower using the AWS S3 Console  (maybe 10-20% slower).

How does your upload time compare to, for example, uploading the same file to Google Drive or an FTP site? What does speedtest report for your ISP connection?

**Comment by gitsapuser** [comment]
LOL, my speed test for upload is 11.69Mbps which explains it all.  You're right, ISP is a big piece of this.  Thank you and kudos to this tool that I find very helpful for my use-case.

**Comment by gitsapuser** [comment]
closed
