### ISSUE TITLE
JSON CORS config in README

### ISSUE THREAD

**Issue by ignatiusm** [awslabs/aws-js-s3-explorer#99]
Current s3 console requires CORS config to be provided in JSON rather than xml . Can you please amend README to show JSON too?

**Comment by john-aws** [comment]
Hi, this seems like a good idea, thanks for raising it. Was there a particular reason you closed the issue?

**Comment by ignatiusm** [comment]
I closed it because I saw that zflamig had a patch to address this. Upon closer inspection I see that zflamig's patch is only for master. I have submitted a PR for the v2-alpha branch.

**Comment by john-aws** [comment]
Merged https://github.com/awslabs/aws-js-s3-explorer/pull/100, thank you.
